server:
  port: 8080
spring:
  security:
    user:
      password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "validate"
  datasource-course:
    url: "jdbc:mysql://localhost:3306/course"
    username: "course"
    password: "course"
erp:
  user: "http://localhost:8081/user"
  educator: "http://localhost:8081/educator"
