server:
  port: 8080
spring:
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: true
      hbm2ddl:
        auto: none
  datasource:
    url: "jdbc:mysql://localhost:3306/course"
    username: "course"
    password: "course"
