server:
  port: 8081
spring:
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "validate"
  datasource-user:
    jdbcUrl: "jdbc:mysql://localhost:3306/user"
    username: "user"
    password: "user"
